//These credentials are usually generated by your server


const apiKey = '47248174';
const sessionId = '1_MX40NzI0ODE3NH5-MTYyMzMyMDA5NjYzMn5ZNGY2RmJkMFdKSXQwc0dYbGVlMmNOVGZ-UH4';
const token4 = "T1==cGFydG5lcl9pZD00NzI0ODE3NCZzaWc9YzdlYTgxODdkZjQ5N2FkM2NiZTMyMDEwMGI1ODRkNWU1Mjc2ODk5YzpzZXNzaW9uX2lkPTFfTVg0ME56STBPREUzTkg1LU1UWXlNek15TURBNU5qWXpNbjVaTkdZMlJtSmtNRmRLU1hRd2MwZFliR1ZsTW1OT1ZHWi1VSDQmY3JlYXRlX3RpbWU9MTYyMzMxOTgxNiZyb2xlPXB1Ymxpc2hlciZub25jZT0xNjIzMzE5ODE2LjI0ODg0NjM1ODg4MyZpbml0aWFsX2xheW91dF9jbGFzc19saXN0PQ==";
const token1 = "T1==cGFydG5lcl9pZD00NzI0ODE3NCZzaWc9YjMwNjNjOTNiZGQxZmQ3YjY3NmQ1ZmM4YWQxZjgwMzk3NzVjZTA4ODpzZXNzaW9uX2lkPTFfTVg0ME56STBPREUzTkg1LU1UWXlNek15TURBNU5qWXpNbjVaTkdZMlJtSmtNRmRLU1hRd2MwZFliR1ZsTW1OT1ZHWi1VSDQmY3JlYXRlX3RpbWU9MTYyMzMxOTg2MSZyb2xlPXB1Ymxpc2hlciZub25jZT0xNjIzMzE5ODYxLjQyMzUxMzkwMTEyMjM1JmluaXRpYWxfbGF5b3V0X2NsYXNzX2xpc3Q9";
const token2 = "T1==cGFydG5lcl9pZD00NzI0ODE3NCZzaWc9NzNkNWUyNDE1NmMwZWNlYjUxMzI0NjUxNjg2NDQ0YWU5ZDE0N2Q3MTpzZXNzaW9uX2lkPTFfTVg0ME56STBPREUzTkg1LU1UWXlNek15TURBNU5qWXpNbjVaTkdZMlJtSmtNRmRLU1hRd2MwZFliR1ZsTW1OT1ZHWi1VSDQmY3JlYXRlX3RpbWU9MTYyMzMxOTg5NyZyb2xlPXB1Ymxpc2hlciZub25jZT0xNjIzMzE5ODk3LjEyODU2MzY4ODI1OTUmaW5pdGlhbF9sYXlvdXRfY2xhc3NfbGlzdD0=";
const token3 = "T1==cGFydG5lcl9pZD00NzI0ODE3NCZzaWc9MmI4Mjk0NTgxZjg0ODY4NzZiYzQ4OTYwMGFmYTE0MjM4YTExNzRjODpzZXNzaW9uX2lkPTFfTVg0ME56STBPREUzTkg1LU1UWXlNek15TURBNU5qWXpNbjVaTkdZMlJtSmtNRmRLU1hRd2MwZFliR1ZsTW1OT1ZHWi1VSDQmY3JlYXRlX3RpbWU9MTYyMzMxOTkzOCZyb2xlPXB1Ymxpc2hlciZub25jZT0xNjIzMzE5OTM4LjMxNzMxNDM2MTc4MDE4JmluaXRpYWxfbGF5b3V0X2NsYXNzX2xpc3Q9";
var layoutEl = document.getElementById("layout");
var layout;


//Handling all of our errors here by alerting them
function handleError(error) {
    if (error) {
        alert(error.message);
    }
}


function updateLayoutValues() {

    layout = initLayoutContainer(layoutEl, {
        maxRatio: 9/16,
        minRatio: 9/16,
        fixedRatio:false,
        alignItems: "center",
        bigPercentage:0.8,
        bigFixedRatio: false,
        bigMaxRatio: 3/2,
        bigMinRatio: 9/16,
        bigFirst: true,
        smallMaxWidth: Infinity,
        smallMaxHeight: Infinity,
        bigMaxWidth: Infinity,
        bigMaxHeight: Infinity,
        bigAlignItems: "center",
        smallAlignItems: "center",
        scaleLastRow: true,
        bigScaleLastRow: true,
    }).layout;
}
updateLayoutValues();
addPublisher();




function addPublisher() {

    var ratios = [4/3, 3/4, 16/9];
    let session = OT.initSession(apiKey, sessionId);
    var el = document.createElement("div");
    el.videoHeight = 480;
    // Pick a random ratio
    var ratio = ratios[Math.round(Math.random() * (ratios.length - 1))];
    el.videoWidth = 480 * ratio;

    var publisher = OT.initPublisher(el, {
        insertMode: 'append',
        width:"100%",
        height:"100%"
    }, handleError);

    //Once a new user joins the stream this automatically Subscribe to the newly created stream
    session.on('streamCreated', function (event) {
        var sub = document.createElement("div");
        session.subscribe(event.stream, sub, {
            insertMode: 'append',
            width:"100%",
            height:"100%"
        }, handleError);
        addSubscriber(sub);
    });


    // Connect to the session
    session.connect(token4, function (error) {
        // If the connection is successful, initialize a publisher and publish to the session
        if (error) {
            handleError(error);
        } else {
            session.publish(publisher, handleError);
            layout();
        }
    });


    el.addEventListener('dblclick', function () {
        if (el.classList.contains('OT_big')) {
            el.classList.remove('OT_big');
        } else {
            el.classList.add('OT_big');
        }
        layout();
    });

    layoutEl.appendChild(el);
    layout();

}

function addSubscriber(sub) {
    sub.videoHeight = 480;
    // Pick a random ratio
    var ratios = [4/3, 3/4, 16/9];
    var ratio = ratios[Math.round(Math.random() * (ratios.length - 1))];
    sub.videoWidth = 480 * ratio;
    sub.addEventListener('dblclick', function () {
        if (sub.classList.contains('OT_big')) {
            sub.classList.remove('OT_big');
        } else {
            sub.classList.add('OT_big');
        }
        layout();
    });
    layoutEl.appendChild(sub);
    layout();
}


function removeElement() {
    layoutEl.firstChild.classList.remove('ot-layout');
    setTimeout(function() {
        layoutEl.removeChild(layoutEl.firstChild);
        layout();
    }, 200);
}

var resizeTimeout;
window.onresize = function() {
    clearTimeout(resizeTimeout);
    resizeTimeout = setTimeout(function () {
        layout();
    }, 20);
};
